### ISSUE TITLE
Needs --filesytem=/tmp

### ISSUE THREAD

**Issue by Waqar144** [flathub/org.kde.kate#25]
Following up from https://github.com/flathub/org.kde.kate/pull/24

> I don't really understand why we need to have /tmp shared? Is this for getting the output of applications that are run outside the Flatpak?

The reason is that Kate invokes processes on the host and then passes the temporary file as an argument.

E.g.,

The new formatter plugin (v23.04) will 
- format a file using for example clangd and read the stdout
- write the stdout into a temporary file
- use `git` to diff the document before formatting with the temporary file
- applies the diff on top of document

Similarly, the project plugin stores the ctag index into a temporary file. This file is passed as an argument to the ctags process.

We use `QTemporaryFile` to create and manage temporary files. 

@travier

**Comment by travier** [comment]
So as I mentioned in https://github.com/flathub/org.kde.kate/pull/24#issuecomment-1467779235, I think it would be really great if Kate could use something like `xdg-run/kate` instead of `/tmp` for temporary files.

**Comment by Waqar144** [comment]
@travier I tried once more to make sure I wasn't getting anything wrong. 

The thing is we want a path that is accessible by both the host and flatpak. If we use $XDG_RUNTIME_DIR/kate, host processes fail to access the temporary files we create. There might be a way to convert xdg-run/kate to a proper host path but I am not sure if that would be a reliable way and most likely that wouldn't be an acceptable solution as it requires us changing + ensuring all the scenarios work.

In contrast, `/tmp` just works. So I think this is the simplest solution that will work for now.

**Comment by travier** [comment]
Did you make sure to grant the Kate Flatpak access to `xdg-run/kate` when testing this?

**Comment by travier** [comment]
OK, so that makes it not a viable solution

**Comment by travier** [comment]
`/tmp` it is 😢
