### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by KhazAkar** [flathub/org.kde.kate#29]
Hi!
Currently, LSP is not working properly/at all when using Kate from flatpak version. Is it possible to get it somehow running?

**Comment by KhazAkar** [comment]
I just seen that newer version is in flathub beta - will try that.

**Comment by KhazAkar** [comment]
Okay, I've managed to get it working after manually instaling kate from json in repo, and LSP is working. What else can be tested to have it promoted to official or be even published to beta.flathub.org?

**Comment by travier** [comment]
You need to use the version of Kate from the Flathub Beta remote: https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by travier** [comment]
I've created https://github.com/flathub/org.kde.kate/issues/31 to track that
