### ISSUE TITLE
Link to flathub does not work

### ISSUE THREAD

**Issue by KhazAkar** [flathub/org.kde.kate#30]
Hi,
I just clicked on flathub link in this repo and directed me to "app not found" page
![Screenshot_20230404-093452_Mull](https://user-images.githubusercontent.com/12693890/229721097-a30a2d83-425c-469f-a13e-9cc7c202369a.png)

**Comment by travier** [comment]
This is expected as the application is only available as Beta.

**Comment by KhazAkar** [comment]
Okay then, thanks :)
