### ISSUE TITLE
Move out of Beta

### ISSUE THREAD

**Issue by travier** [flathub/org.kde.kate#31]
Tracker for things that needs to be resolved to be able to move Kate out of Beta on Flathub.

**Comment by sallyhaj** [comment]
I use the version from Beta, it works just fine.

**Comment by Justinzobel** [comment]
@sallyhaj are you able to have a read through https://invent.kde.org/teams/flathub/issues/-/issues/9 and confirm all the features are now working? If so, we can certainly consider moving this to stable.

**Comment by travier** [comment]
See also the previous discussions in https://github.com/flathub/org.kde.kate/pull/24

**Comment by Waqar144** [comment]
I think we can move to stable. There are bugs, sure, but its pretty usable in general.

**Comment by Justinzobel** [comment]
@travier thoughts on moving to stable? I see from https://github.com/flathub/org.kde.kate/issues/29 that pylsp might need to be added to the Flatpak manifest?

**Comment by Waqar144** [comment]
@travier I think we can move to stable now. See last comments, https://invent.kde.org/teams/flathub/issues/-/issues/9

**Comment by travier** [comment]
OK, let's do this. Can you file an issue in https://github.com/flathub/flathub/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen, link it here and ping me there and I'll vouch for the request? Thanks

**Comment by Waqar144** [comment]
Done: https://github.com/flathub/flathub/issues/5585

**Comment by travier** [comment]
https://flathub.org/apps/org.kde.kate is up and I've clicked the button to mark it as verified, should be visible soon.

The main check failing if for brand colors: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#has-primary-brand-colors

**Comment by Waqar144** [comment]
@travier How do I propose a change to the application description and screenshots that appear on flathub website?

**Comment by travier** [comment]
It's all taken from the appstream metadata that is in the Kate repo: https://invent.kde.org/utilities/kate/-/blob/master/apps/kate/data/org.kde.kate.appdata.xml
