### ISSUE TITLE
No minimize, close and resize buttons on Ubuntu

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.kde.kate#5]
Dear developers,

I installed on an Ubuntu 18.04.4 machine and it does not show any window buttons, or to be specific no minimize, resize or close button.
![Bildschirmfoto vom 2020-03-17 15-17-26](https://user-images.githubusercontent.com/43045863/76865088-722f2f00-6862-11ea-98c1-7bca2b79d3c9.png)
Is this intended or is it a bug?

Regards

Jakob

**Comment by Justinzobel** [comment]
Works fine here. Is this still happening for you?
